dungeon:
    resource: "@DungeonBundle/Resources/config/routing.yml"
    prefix:   /

_bm2_intl:
    resource: "@BM2SiteBundle/Resources/config/routing.yml"
#    prefix:   /
# should work, but doesn't
    prefix:   /{_locale}
    requirements:
     _locale: en|de|fr|it|es|ru
    defaults:
     _locale: en

msg:
    resource: "@MsgBundle/Resources/config/routing.yml"
#    prefix:   /
# should work, but doesn't
    prefix:   /{_locale}
    requirements:
     _locale: en|de|fr|it|es|ru
    defaults:
     _locale: en

fos_user_security_detect:
    prefix:  /{_locale}
    pattern: /detect
    defaults: { _controller: FOSUserBundle:Security:detect }
    requirements:
        _method: GET|POST

_catcher:
 path:	/{url}
 defaults:
  _controller: BM2SiteBundle:Default:localeRedirect
  url:			-
 requirements:
  url:			".+"
